### ISSUE TITLE
In clamav helm chart, tolerations don't work

### ISSUE THREAD

**Issue by asa511** [wiremind/wiremind-helm-charts#147]
In the latest version of clamav chart (2.4.0), I am trying to use tolerations in the values file. 

However, the deployment fails because the indentation is being rendered wrong. I am adding the following lines:

```
tolerations:
  - key: arch
    effect: "Equal"
    value: "arm64"
    effect: "NoSchedule"
```

I get the following error:

```
Error: YAML parse error on clamav/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 54: did not find expected key
```

A solution could be to rewrite the template as:

```
{{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```
