### ISSUE TITLE
cerebro securityContext - empty object not working

### ISSUE THREAD

**Issue by AbbasHallal** [wiremind/wiremind-helm-charts#178]
I am installing cerebro on openshift and I want to set securityContext to null and bind the deployment to `default ` service account, `serviceAccountName: default` so that I can get random number from the allowed range.  However this is not working as expected as it's still setting the default values originally defined
see  
values.yaml:
```
securityContext: {}
```
Deployment:
```
spec:
  securityContext:
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 1000

````
