### ISSUE TITLE
Feat [karma] Some chart values should be evaluated by tpl function

### ISSUE THREAD

**Issue by bkomraz1** [wiremind/wiremind-helm-charts#366]
### Is your feature request related to a problem?

In case of installation of multiple helm chart to multiple environments when charts require definition of values on base environment properties I want to avoid creation multiple value files for each chart

```
karma:
  values.yaml
  values-env1.yaml
  values-env2.yaml
  values-env3.yaml

argocd:
  values.yaml
  values-env1.yaml
  values-env2.yaml
  values-env3.yaml
```

Instead of it I want that values.yaml in each chart will reference values from environment value file that will be used for multiple charts.

```
# values-shared-env1.yaml
global:
  dnsDomain: .my.env.domain
```

```
configMap:
   rawConfig:
     alertmanager:
       servers:
       - name: default
         uri: http://alertmanager:9093
         external_uri: "https://alertmanager{{.Values.global.dnsDomain}}"
  
ingress:
  hosts:
  - "karma{{ .Values.global.dnsDomain }}"
 ```             
  

### Related helm chart

karma

### Describe the solution you'd like

Some values should be evaluated by "tpl" function

```
host: {{ tpl $host .  }}
 ```
